apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mariadb
  name: mariadb-config
data:
  mariadb.cnf: |
    [client]
    default-character-set = utf8
    [mysqld]
    character-set-server  = utf8
    collation-server      = utf8_general_ci
    # InnoDB tuning
    innodb_log_file_size  = 50M